### ISSUE TITLE
Atlas van de verstedelijking geometries need repair

### ISSUE THREAD

**Issue by mmmenno** [erfgoed-en-locatie/data#5]
This list shows how many geometries per town are actually working. Since rather time-consuming, it's probably best to work downwards from the top and hope we can fix 4 or 5 towns for a scaled down version of Niene's app.

Amsterdam **all!**
Groningen 8 van 9
Den Haag 8 van 9
Haarlem 8 van 9
dordrecht 7 van 8
ede 5 van 7
emmen 4 van 6
Delft 4 van 7
Enschede 4 van 7
Eindhoven 4 van 6
heerlen 3 van 7
Arnhem 3 van 7
Breda 2 van 10
Den bosch 2 van 9
Amersfoort 2 van veel
apeldoorn 3 van veel
deventer 2 van 8

Zwolle 0
Rotterdam 0
Leeuwarden 0
Leiden 0
Tilburg 0 
Maastricht 0
nijmegen 0
Almere 0
epe 0
helmond 0
hengelo 0
hilversum 0
utrecht 0
venlo 0
zaanstad 0
zoetermeer 0

**Comment by jobspierings** [comment]
@mmmenno bug or enhancement?

**Comment by mmmenno** [comment]
All fixed, some with Qgis, most miraculously.
